package jumao

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"encoding/binary"
	"encoding/hex"
	"hash/crc32"
	"io"
	"net"
	"testing"
	"time"

	M "github.com/sagernet/sing/common/metadata"
)

// Vectors generated by an independent Python implementation of the documented
// scheme (zlib.crc32 + cryptography AES-CFB), so a drift in either side fails.
const (
	vectorPassword = "jumao-test-pass"
	vectorUserID   = uint32(0x0A0B0C0D)
	vectorUserPass = "node-secret"
	vectorKey      = "8d5cf2ee1939c644a9cf30dc65e51ef6bff8f7ab376c1edac1071963982c29dd"
	vectorIV       = "010203040c0e080e00f153658e3ed258"
	vectorTime     = uint32(1700000000)
)

func TestPasswordKeyVector(t *testing.T) {
	key := PasswordKey(vectorPassword)
	if hex.EncodeToString(key) != vectorKey {
		t.Fatalf("key = %s, want %s", hex.EncodeToString(key), vectorKey)
	}
}

func TestWatermarkIVVector(t *testing.T) {
	iv := WatermarkIV(vectorUserID, vectorUserPass, []byte{1, 2, 3, 4}, vectorTime)
	if hex.EncodeToString(iv) != vectorIV {
		t.Fatalf("iv = %s, want %s", hex.EncodeToString(iv), vectorIV)
	}
	// The second word is R XOR LE32(user_id): that binding is the credential.
	credential := make([]byte, 4)
	binary.LittleEndian.PutUint32(credential, vectorUserID)
	want := make([]byte, 4)
	for i := range want {
		want[i] = iv[i] ^ credential[i]
	}
	if !bytes.Equal(iv[4:8], want) {
		t.Fatalf("iv[4:8] = %x, want %x", iv[4:8], want)
	}
	checksum := crc32.NewIEEE()
	checksum.Write(credential)
	checksum.Write(iv[0:4])
	checksum.Write(iv[8:12])
	checksum.Write([]byte(vectorUserPass))
	if binary.LittleEndian.Uint32(iv[12:16]) != checksum.Sum32() {
		t.Fatalf("iv[12:16] = %x, want CRC32 %x", iv[12:16], checksum.Sum32())
	}
}

func TestEncodeAddrVector(t *testing.T) {
	ipv4, err := EncodeAddr(M.ParseSocksaddr("1.2.3.4:443"))
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(ipv4) != "010102030401bb" {
		t.Fatalf("ipv4 header = %s", hex.EncodeToString(ipv4))
	}
	domain, err := EncodeAddr(M.ParseSocksaddr("www.gstatic.com:80"))
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(domain) != "030f7777772e677374617469632e636f6d0050" {
		t.Fatalf("domain header = %s", hex.EncodeToString(domain))
	}
	if _, err = EncodeAddr(M.ParseSocksaddr("[2001:db8::1]:443")); err == nil {
		t.Fatal("IPv6 destination must be refused")
	}
}

func TestHandshakeVector(t *testing.T) {
	block, err := aes.NewCipher(PasswordKey(vectorPassword))
	if err != nil {
		t.Fatal(err)
	}
	iv, err := hex.DecodeString(vectorIV)
	if err != nil {
		t.Fatal(err)
	}
	stream := cipher.NewCFBEncrypter(block, iv)
	header := []byte{1, 1, 2, 3, 4, 1, 0xbb}
	payload := make([]byte, len(header))
	stream.XORKeyStream(payload, header)
	if hex.EncodeToString(payload) != "d4a47e3f698025" {
		t.Fatalf("encrypted header = %s", hex.EncodeToString(payload))
	}
}

// peer simulates the node over a real TCP connection: it validates the
// watermark exactly as documented, decodes the address header and answers with
// its own IV plus one frame, so both directions are exercised.
func peer(t *testing.T, userID uint32, userPass string) (net.Conn, <-chan []byte, <-chan []byte) {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	addresses := make(chan []byte, 1)
	payloads := make(chan []byte, 1)
	go func() {
		server, err := listener.Accept()
		if err != nil {
			t.Errorf("peer: accept: %v", err)
			return
		}
		defer server.Close()
		defer listener.Close()
		iv := make([]byte, IVSize)
		if _, err = io.ReadFull(server, iv); err != nil {
			t.Errorf("peer: read iv: %v", err)
			return
		}
		credential := make([]byte, 4)
		binary.LittleEndian.PutUint32(credential, userID)
		for i := 0; i < 4; i++ {
			if iv[4+i] != iv[i]^credential[i] {
				t.Errorf("peer: watermark credential mismatch at %d", i)
				return
			}
		}
		checksum := crc32.NewIEEE()
		checksum.Write(credential)
		checksum.Write(iv[0:4])
		checksum.Write(iv[8:12])
		checksum.Write([]byte(userPass))
		if binary.LittleEndian.Uint32(iv[12:16]) != checksum.Sum32() {
			t.Errorf("peer: watermark checksum mismatch")
			return
		}
		if drift := time.Since(time.Unix(int64(binary.LittleEndian.Uint32(iv[8:12])), 0)); drift > time.Minute || drift < -time.Minute {
			t.Errorf("peer: timestamp drift %s", drift)
			return
		}
		block, err := aes.NewCipher(PasswordKey(vectorPassword))
		if err != nil {
			t.Errorf("peer: cipher: %v", err)
			return
		}
		stream := cipher.NewCFBDecrypter(block, iv)
		readClear := func(length int) ([]byte, bool) {
			encrypted := make([]byte, length)
			if _, err := io.ReadFull(server, encrypted); err != nil {
				t.Errorf("peer: read %d bytes: %v", length, err)
				return nil, false
			}
			clear := make([]byte, length)
			stream.XORKeyStream(clear, encrypted)
			return clear, true
		}
		atyp, ok := readClear(1)
		if !ok {
			return
		}
		var address []byte
		switch atyp[0] {
		case 1:
			rest, ok := readClear(4 + 2)
			if !ok {
				return
			}
			address = append([]byte{1}, rest...)
		case 3:
			head, ok := readClear(1)
			if !ok {
				return
			}
			rest, ok := readClear(int(head[0]) + 2)
			if !ok {
				return
			}
			address = append([]byte{3, head[0]}, rest...)
		default:
			t.Errorf("peer: bad atyp %d", atyp[0])
			return
		}
		addresses <- address
		peerIV := bytes.Repeat([]byte{9}, IVSize)
		if _, err = server.Write(peerIV); err != nil {
			t.Errorf("peer: write iv: %v", err)
			return
		}
		reply := []byte("HTTP/1.1 204 No Content")
		out := cipher.NewCFBEncrypter(block, peerIV)
		encryptedReply := make([]byte, len(reply))
		out.XORKeyStream(encryptedReply, reply)
		if _, err = server.Write(encryptedReply); err != nil {
			t.Errorf("peer: write reply: %v", err)
			return
		}
		// The payload written by the client keeps using the header stream.
		payload, ok := readClear(5)
		if !ok {
			return
		}
		payloads <- payload
	}()
	client, err := net.Dial("tcp", listener.Addr().String())
	if err != nil {
		t.Fatal(err)
	}
	return client, addresses, payloads
}

func TestHandshakeRoundTrip(t *testing.T) {
	client, addresses, payloads := peer(t, vectorUserID, vectorUserPass)
	conn, err := Handshake(client, vectorPassword, vectorUserID, vectorUserPass, M.ParseSocksaddr("www.gstatic.com:80"))
	if err != nil {
		t.Fatal(err)
	}
	select {
	case address := <-addresses:
		want := []byte{3, 15, 'w', 'w', 'w', '.', 'g', 's', 't', 'a', 't', 'i', 'c', '.', 'c', 'o', 'm', 0, 80}
		if !bytes.Equal(address, want) {
			t.Fatalf("peer decoded address %x, want %x", address, want)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("peer never decoded the address header")
	}
	if _, err = conn.Write([]byte{1, 2, 3, 4, 5}); err != nil {
		t.Fatal(err)
	}
	reply := make([]byte, len("HTTP/1.1 204 No Content"))
	if _, err = io.ReadFull(conn, reply); err != nil {
		t.Fatal(err)
	}
	if string(reply) != "HTTP/1.1 204 No Content" {
		t.Fatalf("client decoded %q", reply)
	}
	if !conn.(*Conn).PeerIV() {
		t.Fatal("peer IV was never consumed")
	}
	select {
	case payload := <-payloads:
		if !bytes.Equal(payload, []byte{1, 2, 3, 4, 5}) {
			t.Fatalf("peer decrypted payload %v", payload)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("peer never received the payload")
	}
}

func TestWatermarkRejectsWrongCredential(t *testing.T) {
	iv := WatermarkIV(vectorUserID, vectorUserPass, []byte{1, 2, 3, 4}, vectorTime)
	other := WatermarkIV(vectorUserID+1, vectorUserPass, []byte{1, 2, 3, 4}, vectorTime)
	if bytes.Equal(iv, other) {
		t.Fatal("a different user id must produce a different watermark")
	}
	checksum := crc32.NewIEEE()
	checksum.Write([]byte{9, 9, 9, 9})
	if binary.LittleEndian.Uint32(iv[12:16]) == checksum.Sum32() {
		t.Fatal("checksum must bind the real credential")
	}
}
